# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OmaniRecipeV1.1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OmaniRecipeV1.1
  pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'AKSideMenu'
pod 'Parchment'
#pod 'Kingfisher', '~> 4.0'


end
